(function(){
'use strict';
var BM={loaded:false,loading:false,items:[],duplicates:[],selected:{},q:'',group:'',status:'',showDuplicates:true,action:'',step:1,payload:{},requestId:''};
var META={
  arrived:{title:'สินค้ามาแล้ว',sub:'เปลี่ยนจาก รอสินค้า เป็น ของมาแล้ว',status:['รอสินค้า']},
  appointment:{title:'ตั้งวันนัดรับ',sub:'กำหนดวันและเวลาให้ทุกรายการ',status:['ของมาแล้ว','นัดรับแล้ว']},
  call:{title:'บันทึกผลการโทร',sub:'ผลการติดต่อและหมายเหตุร่วมกัน',status:['รอตรวจสอบ','รอสินค้า','ของมาแล้ว','นัดรับแล้ว']},
  note:{title:'เพิ่มหมายเหตุ',sub:'บันทึกข้อความเดียวกันให้หลายออเดอร์',status:null},
  done:{title:'รับสินค้าแล้ว',sub:'ยืนยันและปิดหลายรายการพร้อมกัน',status:['นัดรับแล้ว']}
};
function el(id){return document.getElementById(id)}
function safe(s){return typeof esc==='function'?esc(s):String(s==null?'':s).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
function uuid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}
function active(){var page=el('pg-bulk');return page&&page.classList.contains('on')}
function selectedItems(){return BM.items.filter(function(x){return BM.selected[x.id]})}
function eligible(item,action){var allowed=META[action].status;return !allowed||allowed.indexOf(item.status)>-1}
function filtered(){var q=BM.q.trim().toLowerCase();return BM.items.filter(function(x){if(BM.group&&x.group!==BM.group)return false;if(BM.status&&x.status!==BM.status)return false;if(q&&[x.id,x.name,x.phone,x.model,x.capacity,x.color,x.group].join(' ').toLowerCase().indexOf(q)<0)return false;return true})}
function groups(){var out={};filtered().forEach(function(x){var key=(x.phone||'')+'|'+(x.name||'');(out[key]||(out[key]=[])).push(x)});return Object.keys(out).map(function(k){return out[k]})}
function statusClass(s){return s==='ของมาแล้ว'?'arrived':s==='นัดรับแล้ว'?'appt':s==='รับของแล้ว'?'done':''}
function unique(field){return Array.from(new Set(BM.items.map(function(x){return x[field]}).filter(Boolean))).sort()}
function option(value,current){return '<option value="'+safe(value)+'"'+(value===current?' selected':'')+'>'+safe(value)+'</option>'}
function shell(){var root=el('bulk-root');if(!root)return;root.innerHTML='<div class="bm-shell"><div class="bm-top"><div><h1 class="bm-title">จัดการหลายรายการ</h1><p class="bm-lead">เลือกหลายเครื่อง ตรวจสอบผลกระทบ และบันทึกครั้งเดียวอย่างปลอดภัย</p></div><button class="bm-refresh" id="bm-refresh" type="button">↻ รีเฟรช</button></div><div id="bm-body"></div></div>';el('bm-refresh').onclick=function(){load(true)}}
function duplicateHtml(){if(!BM.duplicates.length)return '<div class="bm-insight"><div class="bm-insight-copy"><span class="bm-insight-icon">✓</span><div><b>ไม่พบรายการที่น่าจะซ้ำ</b><small>ตรวจจากการส่งสเปกซ้ำและการส่งข้อมูลซ้ำใน 15 นาที</small></div></div><span class="bm-insight-count">0</span></div>';
var list=BM.showDuplicates?'<div class="bm-duplicate-list">'+BM.duplicates.map(function(d){return '<div class="bm-duplicate '+safe(d.severity)+'"><span class="bm-severity"></span><div><b>'+safe(d.name)+' · '+safe(d.phone)+'</b><small>'+safe(d.detail)+' · '+safe(d.spec)+'</small></div><div class="bm-duplicate-ids">'+d.ids.map(function(id){return '<button class="bm-id" data-bm-open="'+safe(id)+'">'+safe(id)+'</button>'}).join('')+'</div></div>'}).join('')+'</div>':'';
return '<button class="bm-insight" id="bm-toggle-duplicates" type="button"><div class="bm-insight-copy"><span class="bm-insight-icon">⚠</span><div><b>พบรายการที่ควรตรวจสอบว่าซ้ำหรือไม่</b><small>กดเพื่อ'+(BM.showDuplicates?'ซ่อน':'ดู')+'รายละเอียด · ระบบยังไม่ลบรายการให้อัตโนมัติ</small></div></div><span class="bm-insight-count">'+BM.duplicates.length+'</span></button>'+list}
function filterHtml(){return '<div class="bm-filter"><div class="field"><label>ค้นหา</label><input id="bm-q" type="search" value="'+safe(BM.q)+'" placeholder="ชื่อ เบอร์ เลขออเดอร์ หรือรุ่น"></div><div class="field"><label>กลุ่มลูกค้า</label><select id="bm-group"><option value="">ทุกกลุ่ม</option>'+unique('group').map(function(x){return option(x,BM.group)}).join('')+'</select></div><div class="field"><label>สถานะ</label><select id="bm-status"><option value="">ทุกสถานะ</option>'+unique('status').map(function(x){return option(x,BM.status)}).join('')+'</select></div><button class="btn2" id="bm-select-visible" type="button">เลือกที่แสดง</button><button class="btn2" id="bm-clear" type="button">ล้างที่เลือก</button></div>'}
function actionsHtml(){var count=selectedItems().length;return '<div class="bm-actions">'+Object.keys(META).map(function(k){var m=META[k];return '<button class="bm-action" data-bm-action="'+k+'" '+(!count?'disabled':'')+'><b>'+safe(m.title)+'</b><small>'+safe(m.sub)+'</small></button>'}).join('')+'</div>'}
function itemHtml(x){return '<label class="bm-item"><input type="checkbox" data-bm-id="'+safe(x.id)+'" '+(BM.selected[x.id]?'checked':'')+'><div><button class="bm-item-id" data-bm-open="'+safe(x.id)+'" type="button">'+safe(x.id)+'</button><small>'+safe(x.group)+'</small></div><div><b>'+safe(x.model)+'</b><small>'+safe(x.capacity)+' · '+safe(x.color)+'</small></div><span class="bm-status '+statusClass(x.status)+'">'+safe(x.status)+'</span><span class="bm-appt">'+safe(x.appt||x.dueDate||'ยังไม่มีวันนัด')+'</span></label>'}
function listHtml(){var gs=groups(),visible=filtered();if(!gs.length)return '<div class="bm-empty"><b>ไม่พบรายการที่ตรงเงื่อนไข</b>ลองปรับตัวกรองหรือคำค้นหา</div>';return '<div class="bm-summary"><span>แสดง <b>'+visible.length+'</b> รายการ · เลือกแล้ว <b>'+selectedItems().length+'</b></span><span>สูงสุด 100 รายการ/ครั้ง</span></div><div class="bm-groups">'+gs.map(function(rows){var head=rows[0],all=rows.every(function(x){return BM.selected[x.id]});return '<section class="bm-group"><div class="bm-group-head"><input type="checkbox" data-bm-group="'+safe(head.phone+'|'+head.name)+'" '+(all?'checked':'')+'><div><b>'+safe(head.name)+'</b><small>'+safe(head.phone)+' · '+safe(head.group)+'</small></div><span class="bm-group-count">'+rows.length+' เครื่อง</span></div>'+rows.map(itemHtml).join('')+'</section>'}).join('')+'</div>'}
function render(){if(!el('bm-body'))shell();var body=el('bm-body');if(BM.loading){body.innerHTML=typeof loadingHtml==='function'?loadingHtml('กำลังเตรียมพื้นที่จัดการหลายรายการ…'):'กำลังโหลด…';return}body.innerHTML=duplicateHtml()+filterHtml()+actionsHtml()+listHtml()+'<div class="bm-bar" id="bm-bar" '+(selectedItems().length?'':'hidden')+'><div><b>'+selectedItems().length+'</b><span>รายการที่เลือก</span></div><div class="bm-bar-actions"><button class="btn2" id="bm-bar-clear">ล้าง</button><button class="btn" id="bm-bar-next">เลือกคำสั่ง</button></div></div>';bind()}
function rerenderKeepFocus(id){render();var x=el(id);if(x){x.focus();x.setSelectionRange&&x.setSelectionRange(x.value.length,x.value.length)}}
function bind(){var q=el('bm-q');q.oninput=function(){BM.q=q.value;rerenderKeepFocus('bm-q')};el('bm-group').onchange=function(){BM.group=this.value;render()};el('bm-status').onchange=function(){BM.status=this.value;render()};el('bm-clear').onclick=clear;el('bm-select-visible').onclick=function(){var rows=filtered(),newRows=rows.filter(function(x){return !BM.selected[x.id]});if(selectedItems().length+newRows.length>100){toast('เลือกได้สูงสุด 100 รายการ กรุณาล้างรายการที่เลือกหรือกรองให้แคบลง');return}rows.forEach(function(x){BM.selected[x.id]=true});render()};var toggle=el('bm-toggle-duplicates');if(toggle)toggle.onclick=function(){BM.showDuplicates=!BM.showDuplicates;render()};document.querySelectorAll('[data-bm-id]').forEach(function(x){x.onchange=function(){if(x.checked&&selectedItems().length>=100){x.checked=false;toast('เลือกได้สูงสุด 100 รายการ');return}if(x.checked)BM.selected[x.dataset.bmId]=true;else delete BM.selected[x.dataset.bmId];render()}});document.querySelectorAll('[data-bm-group]').forEach(function(x){x.onchange=function(){var key=x.dataset.bmGroup,rows=filtered().filter(function(i){return i.phone+'|'+i.name===key});if(x.checked&&selectedItems().length+rows.filter(function(i){return !BM.selected[i.id]}).length>100){toast('เลือกได้สูงสุด 100 รายการ');render();return}rows.forEach(function(i){if(x.checked)BM.selected[i.id]=true;else delete BM.selected[i.id]});render()}});document.querySelectorAll('[data-bm-action]').forEach(function(x){x.onclick=function(){openAction(x.dataset.bmAction)}});document.querySelectorAll('[data-bm-open]').forEach(function(x){x.onclick=function(e){e.preventDefault();e.stopPropagation();if(typeof openDetail==='function')openDetail(x.dataset.bmOpen)}});if(el('bm-bar-clear'))el('bm-bar-clear').onclick=clear;if(el('bm-bar-next'))el('bm-bar-next').onclick=function(){toast('เลือกคำสั่งจากการ์ดด้านบน')}}
function clear(){BM.selected={};render()}
function ensureModal(){if(el('bm-modal-shade'))return;var d=document.createElement('div');d.id='bm-modal-shade';d.className='bm-modal-shade';d.innerHTML='<div class="bm-modal" role="dialog" aria-modal="true"><div class="bm-modal-head"><div><h2 id="bm-modal-title"></h2><p id="bm-modal-sub"></p></div><button class="bm-close" id="bm-modal-close" aria-label="ปิด">×</button></div><div id="bm-modal-body"></div><div class="bm-modal-actions" id="bm-modal-actions"></div></div>';document.body.appendChild(d);el('bm-modal-close').onclick=closeModal;d.onclick=function(e){if(e.target===d)closeModal()}}
function closeModal(){var m=el('bm-modal-shade');if(m)m.classList.remove('on')}
function openAction(action){var rows=selectedItems();if(!rows.length)return;BM.action=action;BM.step=1;BM.payload={};BM.requestId=uuid();ensureModal();el('bm-modal-title').textContent=META[action].title;el('bm-modal-sub').textContent=rows.length+' รายการที่เลือก';renderModal();el('bm-modal-shade').classList.add('on')}
function invalid(){return selectedItems().filter(function(x){return !eligible(x,BM.action)})}
function formHtml(){var bad=invalid(),p=BM.payload||{},h=bad.length?'<div class="bm-warning">มี '+bad.length+' รายการที่สถานะไม่ตรงเงื่อนไข ระบบจะไม่บันทึกจนกว่าจะเลือกให้ถูกต้อง</div>':'';if(BM.action==='appointment')h+='<div class="field"><label>วันและเวลานัดรับ</label><input id="bm-appt" type="datetime-local" value="'+safe(p._input||'')+'"></div>';if(BM.action==='call')h+='<div class="field"><label>ผลการติดต่อ</label><select id="bm-call"><option value="">กรุณาระบุ</option>'+[['notified','แจ้งลูกค้าแล้ว'],['ok','ยืนยันนัดรับตามเดิม'],['no_answer','ลูกค้าไม่รับสาย'],['busy','ติดต่อไม่ได้'],['other','อื่นๆ']].map(function(o){return '<option value="'+o[0]+'"'+(p.call_result===o[0]?' selected':'')+'>'+o[1]+'</option>'}).join('')+'</select></div><div class="field"><label>รายละเอียดเพิ่มเติม (ถ้ามี)</label><textarea id="bm-call-note" maxlength="1000">'+safe(p.note||'')+'</textarea></div>';if(BM.action==='note')h+='<div class="field"><label>หมายเหตุที่จะบันทึกให้ทุกออเดอร์</label><textarea id="bm-note" maxlength="1000" placeholder="เช่น Ref: Milk ECOM หรือ ลูกค้าขอให้โทรช่วงบ่าย">'+safe(p.note||'')+'</textarea></div>';if(BM.action==='done')h+='<div class="bm-warning">การยืนยันจะปิดทุกรายการที่เลือก กรุณาตรวจสอบว่าลูกค้ารับเครื่องครบแล้วจริง</div><label style="display:flex;gap:9px;align-items:flex-start;font-weight:600"><input id="bm-done-check" type="checkbox" style="width:19px;height:19px;margin:0" '+(p._checked?'checked':'')+'>ฉันตรวจสอบแล้วว่าลูกค้ารับสินค้าครบถ้วน</label>';return h}
function reviewHtml(){var rows=selectedItems(),details=BM.action==='appointment'?(BM.payload._display||'วันและเวลานัดรับ'):BM.action==='call'?(BM.payload._display||'ผลการโทร'):BM.action==='note'?(BM.payload._display||'หมายเหตุ'):'';return '<div class="bm-review"><div class="bm-review-card"><b>'+safe(META[BM.action].title)+' · '+rows.length+' รายการ</b><small>'+safe(details||META[BM.action].sub)+'</small></div>'+rows.slice(0,6).map(function(x){return '<div class="bm-review-card"><b>'+safe(x.id)+' · '+safe(x.name)+'</b><small>'+safe(x.model)+' '+safe(x.capacity)+' · '+safe(x.status)+'</small></div>'}).join('')+(rows.length>6?'<small style="color:var(--t2)">และอีก '+(rows.length-6)+' รายการ</small>':'')+'</div><div class="bm-warning">โปรดตรวจสอบรายการและผลลัพธ์อีกครั้ง ระบบจะบันทึกประวัติให้ทุกออเดอร์</div>'}
function renderModal(){var bad=invalid(),body=el('bm-modal-body'),actions=el('bm-modal-actions');body.innerHTML=BM.step===1?formHtml():reviewHtml();actions.innerHTML=BM.step===1?'<button class="btn2" id="bm-modal-cancel">ยกเลิก</button><button class="bm-confirm" id="bm-modal-review" '+(bad.length?'disabled':'')+'>ตรวจสอบก่อนบันทึก</button>':'<button class="btn2" id="bm-modal-back">กลับไปแก้ไข</button><button class="bm-confirm '+(BM.action==='done'?'danger':'')+'" id="bm-modal-confirm">ยืนยันและบันทึก</button>';if(el('bm-modal-cancel'))el('bm-modal-cancel').onclick=closeModal;if(el('bm-modal-review'))el('bm-modal-review').onclick=review;if(el('bm-modal-back'))el('bm-modal-back').onclick=function(){BM.step=1;renderModal()};if(el('bm-modal-confirm'))el('bm-modal-confirm').onclick=execute}
function review(){var p={};if(BM.action==='appointment'){var v=el('bm-appt').value;if(!v){toast('กรุณาระบุวันและเวลานัดรับ');return}p._input=v;p.appointment_at=new Date(v).toISOString();p._display=new Date(v).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'})}if(BM.action==='call'){p.call_result=el('bm-call').value;p.note=el('bm-call-note').value.trim();if(!p.call_result){toast('กรุณาระบุผลการติดต่อ');return}p._display=el('bm-call').selectedOptions[0].textContent+(p.note?' · '+p.note:'')}if(BM.action==='note'){p.note=el('bm-note').value.trim();if(!p.note){toast('กรุณาใส่หมายเหตุ');return}p._display=p.note}if(BM.action==='done'){if(!el('bm-done-check').checked){toast('กรุณาติ๊กยืนยันว่าลูกค้ารับสินค้าครบแล้ว');return}p._checked=true}BM.payload=p;BM.step=2;renderModal()}
function execute(){var rows=selectedItems(),payload=Object.assign({},BM.payload);delete payload._display;delete payload._input;delete payload._checked;var btn=el('bm-modal-confirm');btn.disabled=true;btn.textContent='กำลังบันทึก…';callApi('performBatchAction',{requestId:BM.requestId,action:BM.action,ids:rows.map(function(x){return x.id}),payload:payload,actor:(window.STATE&&STATE.boot&&STATE.boot.user)||'Staff'}).then(function(r){closeModal();BM.selected={};BM.loaded=false;if(typeof markQueueViewsStale==='function')markQueueViewsStale();if(typeof showDonePopup==='function')showDonePopup('บันทึกหลายรายการแล้ว','ดำเนินการสำเร็จ '+(r.count||rows.length)+' รายการ และบันทึกประวัติแล้ว');load(true)}).catch(function(e){btn.disabled=false;btn.textContent='ยืนยันและบันทึก';toast(e.message||'บันทึกไม่สำเร็จ')})}
function load(force){if(BM.loading)return;if(BM.loaded&&!force){render();return}shell();BM.loading=true;render();callApi('getBulkWorkspace').then(function(data){BM.items=data.items||[];BM.duplicates=data.duplicateCandidates||[];BM.loaded=true;BM.loading=false;render()}).catch(function(e){BM.loading=false;el('bm-body').innerHTML='<div class="bm-empty"><b>โหลดข้อมูลไม่สำเร็จ</b>'+safe(e.message)+'</div>'})}
window.bmOpen=function(){if(!active())return;load(false)};
window.bmMarkStale=function(){BM.loaded=false};
})();
